// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeUEzhCaWXR9mihkeOf1JKolQd6Id8KmQ',
    appId: '1:145870218731:web:3e64777f80dd32a139e5ae',
    messagingSenderId: '145870218731',
    projectId: 'fabrica-de-software-de220',
    authDomain: 'fabrica-de-software-de220.firebaseapp.com',
    storageBucket: 'fabrica-de-software-de220.firebasestorage.app',
    measurementId: 'G-D4JR2H504F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0GykyiMxLSdQAwAFKvVa52xX3qwAjgjk',
    appId: '1:145870218731:android:570fec74dacffcdc39e5ae',
    messagingSenderId: '145870218731',
    projectId: 'fabrica-de-software-de220',
    storageBucket: 'fabrica-de-software-de220.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwl_IBNC41-RkXSIY4ATS_kWknCUo-WhY',
    appId: '1:145870218731:ios:37ea6a2c685268ad39e5ae',
    messagingSenderId: '145870218731',
    projectId: 'fabrica-de-software-de220',
    storageBucket: 'fabrica-de-software-de220.firebasestorage.app',
    iosClientId: '145870218731-bvjrrl19snhgfod6coo8qsi81i630uio.apps.googleusercontent.com',
    iosBundleId: 'com.seunome.fabricaSoftwareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwl_IBNC41-RkXSIY4ATS_kWknCUo-WhY',
    appId: '1:145870218731:ios:37ea6a2c685268ad39e5ae',
    messagingSenderId: '145870218731',
    projectId: 'fabrica-de-software-de220',
    storageBucket: 'fabrica-de-software-de220.firebasestorage.app',
    iosClientId: '145870218731-bvjrrl19snhgfod6coo8qsi81i630uio.apps.googleusercontent.com',
    iosBundleId: 'com.seunome.fabricaSoftwareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeUEzhCaWXR9mihkeOf1JKolQd6Id8KmQ',
    appId: '1:145870218731:web:af326f8ff7bd47d739e5ae',
    messagingSenderId: '145870218731',
    projectId: 'fabrica-de-software-de220',
    authDomain: 'fabrica-de-software-de220.firebaseapp.com',
    storageBucket: 'fabrica-de-software-de220.firebasestorage.app',
    measurementId: 'G-VJED17BVSS',
  );
}
